// Auto-generated by adk sync
// Agent: /agents/@clock
// Tools: 3

export interface AgentsClockTools {
  /** Manage recurring loops that fire on a period.

Actions:
- create: Create a new loop (requires operation, periodMs, prompt OR callback, branchId)
- list: List loops (optional status filter)
- get: Get loop by id
- cancel: Cancel loop by id

Example create:
{"operation": "create", "periodMs": 300000, "prompt": "Check system health", "branchId": "new"}

Example with callback:
{"operation": "create", "periodMs": 3600000, "callback": {"action": "execute_tool", "path": "/agents/@worker", "tool": "cleanup"}, "branchId": "new"} */
  "loop": {
    name: "loop";
    description: "Manage recurring loops that fire on a period.\n\nActions:\n- create: Create a new loop (requires operation, periodMs, prompt OR callback, branchId)\n- list: List loops (optional status filter)\n- get: Get loop by id\n- cancel: Cancel loop by id\n\nExample create:\n{\"operation\": \"create\", \"periodMs\": 300000, \"prompt\": \"Check system health\", \"branchId\": \"new\"}\n\nExample with callback:\n{\"operation\": \"create\", \"periodMs\": 3600000, \"callback\": {\"action\": \"execute_tool\", \"path\": \"/agents/@worker\", \"tool\": \"cleanup\"}, \"branchId\": \"new\"}";
    params: Record<string, unknown>;
  };
  /** Get the current time. Returns ISO, unix timestamp, and human-readable format. */
  "time": {
    name: "time";
    description: "Get the current time. Returns ISO, unix timestamp, and human-readable format.";
    params: Record<string, unknown>;
  };
  /** Manage one-shot timers that fire at a scheduled time.

Operations:
- create: Create a new timer (requires operation, delayMs OR fireAt, prompt OR callback, branchId)
- list: List timers (optional status filter)
- get: Get timer by id
- cancel: Cancel timer by id

Example create:
{"operation": "create", "delayMs": 60000, "prompt": "Time to check in", "branchId": "self"}

Example with callback:
{"operation": "create", "fireAt": "2026-03-12T17:00:00Z", "callback": {"action": "invoke", "path": "/agents/atlas-slack", "prompt": "Send reminder"}, "branchId": "new"} */
  "timer": {
    name: "timer";
    description: "Manage one-shot timers that fire at a scheduled time.\n\nOperations:\n- create: Create a new timer (requires operation, delayMs OR fireAt, prompt OR callback, branchId)\n- list: List timers (optional status filter)\n- get: Get timer by id\n- cancel: Cancel timer by id\n\nExample create:\n{\"operation\": \"create\", \"delayMs\": 60000, \"prompt\": \"Time to check in\", \"branchId\": \"self\"}\n\nExample with callback:\n{\"operation\": \"create\", \"fireAt\": \"2026-03-12T17:00:00Z\", \"callback\": {\"action\": \"invoke\", \"path\": \"/agents/atlas-slack\", \"prompt\": \"Send reminder\"}, \"branchId\": \"new\"}";
    params: Record<string, unknown>;
  };
}

export declare const tools: (keyof AgentsClockTools)[];
