// Auto-generated by adk sync
// Agent: /agents/@workspace
// Tools: 2

export interface AgentsWorkspaceTools {
  /** Call any tool on the branch's microVM MCP server.

Available tools:
- run_terminal_cmd: Execute shell commands
- read_file: Read file contents (with optional offset/limit)
- write: Create/overwrite a file
- search_replace: Find and replace text in a file
- delete_file: Delete a file
- list_dir: List directory contents
- grep: Search file contents (uses ripgrep) */
  "call_workspace_tool": {
    name: "call_workspace_tool";
    description: "Call any tool on the branch's microVM MCP server.\n\nAvailable tools:\n- run_terminal_cmd: Execute shell commands\n- read_file: Read file contents (with optional offset/limit)\n- write: Create/overwrite a file\n- search_replace: Find and replace text in a file\n- delete_file: Delete a file\n- list_dir: List directory contents\n- grep: Search file contents (uses ripgrep)";
    params: Record<string, unknown>;
  };
  /** Execute a shell command in the branch's isolated microVM container.

The microVM has:
- Ubuntu 24.04 with Node 22, Bun, git, jq, ripgrep
- Pre-installed SDKs: @datadog/datadog-api-client, @temporalio/client, snowflake-sdk, pg, @slack/web-api
- @slashfi/atlas-runtime SDK for calling back to Atlas
- Working directory: /workspace/scripts/

IMPORTANT:
- Commands run in a non-interactive shell
- Default timeout is 30 seconds
- Use is_background: true for long-running commands
- Use head/tail to limit large outputs */
  "run_command": {
    name: "run_command";
    description: "Execute a shell command in the branch's isolated microVM container.\n\nThe microVM has:\n- Ubuntu 24.04 with Node 22, Bun, git, jq, ripgrep\n- Pre-installed SDKs: @datadog/datadog-api-client, @temporalio/client, snowflake-sdk, pg, @slack/web-api\n- @slashfi/atlas-runtime SDK for calling back to Atlas\n- Working directory: /workspace/scripts/\n\nIMPORTANT:\n- Commands run in a non-interactive shell\n- Default timeout is 30 seconds\n- Use is_background: true for long-running commands\n- Use head/tail to limit large outputs";
    params: Record<string, unknown>;
  };
}

export declare const tools: (keyof AgentsWorkspaceTools)[];
