/**
 * Ref Materialization — Download agent docs to local filesystem.
 *
 * When `adk ref add` succeeds, materialize the agent's tool schemas,
 * resources (skills), and generate TypeScript type definitions locally.
 *
 * Files are written under the adk config dir at refs/<name>/.
 */

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import type { Adk } from "./config-store.js";
// No init imports needed — materialize is self-contained

// ============================================
// Types
// ============================================

interface ToolSchema {
  name: string;
  description?: string;
  inputSchema?: Record<string, unknown>;
  outputSchema?: Record<string, unknown>;
}

interface MaterializeResult {
  toolCount: number;
  skillCount: number;
  typesGenerated: boolean;
}

// ============================================
// Helpers
// ============================================

function ensureWrite(path: string, content: string): void {
  const dir = dirname(path);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
  writeFileSync(path, content, "utf-8");
}

/** Generate a .d.ts file from tool schemas. */
function generateTypes(refName: string, tools: ToolSchema[]): string {
  const lines: string[] = [
    `// Auto-generated by adk ref add`,
    `// Agent: ${refName}`,
    `// Tools: ${tools.length}`,
    ``,
    `export interface ${pascalCase(refName)}Tools {`,
  ];

  for (const tool of tools) {
    lines.push(`  /** ${tool.description ?? tool.name} */`);
    lines.push(`  ${JSON.stringify(tool.name)}: {`);
    lines.push(`    name: ${JSON.stringify(tool.name)};`);
    if (tool.description) {
      lines.push(`    description: ${JSON.stringify(tool.description)};`);
    }
    lines.push(`    params: Record<string, unknown>;`);
    lines.push(`  };`);
  }

  lines.push(`}`);
  lines.push(``);
  lines.push(`export declare const tools: (keyof ${pascalCase(refName)}Tools)[];`);
  lines.push(``);
  return lines.join("\n");
}

function pascalCase(s: string): string {
  return s
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase())
    .replace(/^./, (c) => c.toUpperCase());
}

// ============================================
// Materialize
// ============================================

export async function materializeRef(
  adk: Adk,
  refName: string,
  configDir: string,
): Promise<MaterializeResult> {
  const refDir = join(configDir, "refs", refName);
  const toolsDir = join(refDir, "tools");
  const skillsDir = join(refDir, "skills");
  const typesDir = join(refDir, "types");

  let toolCount = 0;
  let skillCount = 0;
  let typesGenerated = false;

  // 1. Fetch and write tool schemas
  try {
    const info = await adk.ref.inspect(refName, { full: true });
    if (info?.tools && info.tools.length > 0) {
      const tools: ToolSchema[] = info.tools.map((t: any) => ({
        name: t.name,
        description: t.description,
        inputSchema: t.inputSchema,
        outputSchema: t.outputSchema,
      }));

      for (const tool of tools) {
        const safeName = tool.name.replace(/[^a-zA-Z0-9_-]/g, "_");
        ensureWrite(
          join(toolsDir, `${safeName}.tool.json`),
          JSON.stringify(tool, null, 2),
        );
      }
      toolCount = tools.length;

      // Write agent.json metadata
      ensureWrite(
        join(refDir, "agent.json"),
        JSON.stringify({
          name: refName,
          description: info.description,
          toolCount: tools.length,
          tools: tools.map((t) => t.name),
          materializedAt: new Date().toISOString(),
        }, null, 2),
      );

      // Generate .d.ts
      ensureWrite(
        join(typesDir, `${refName}.d.ts`),
        generateTypes(refName, tools),
      );
      typesGenerated = true;
    }
  } catch {
    // inspect failed — agent might not be reachable yet (needs auth)
  }

  // 2. Fetch and write resources (skills)
  try {
    const resourcesResult = await adk.ref.resources(refName);
    const response = resourcesResult as any;
    if (response?.result?.resources) {
      for (const resource of response.result.resources) {
        if (resource.uri && resource.text) {
          const filename = resource.uri.split("/").pop() ?? "resource.md";
          ensureWrite(join(skillsDir, filename), resource.text);
          skillCount++;
        }
      }
    }
  } catch {
    // resources fetch failed — might not be supported
  }

  return { toolCount, skillCount, typesGenerated };
}

